apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  namespace: koreanmate
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
          - path: /correction
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
          - path: /conversation
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
          - path: /level-test
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80