apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: koreanmate
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::127696278675:role/koreanmate-dev-eks-cluster-backend-pod-role
