import { generateText } from "../external/bedrockClient.js";
import { saveLearningRecord } from "../repositories/learningRecordRepository.js";
import {
  checkUsageLimit,
  incrementUsage,
} from "../repositories/usageLimitRepository.js";
import { getOrCreateUserProfile } from "./profileService.js";
import type {
  AiResponse,
  CorrectionResultData,
} from "../types/aiResult.js";

export type CorrectionInput = {
  text?: string;
};

export type CorrectionServiceResult = AiResponse<
  "correction",
  CorrectionResultData
>;

function buildCorrectionPrompt(inputText: string, levelLabel: string, explanationLanguage: string) {
  return `
User Korean level: ${levelLabel}
Explanation language: ${explanationLanguage}

You are a Korean tutor for foreign learners.

Correct the following Korean text.
Return the answer with:
1. Corrected Korean sentence
2. English explanation
3. Grammar points
4. Natural English meaning

Text:
${inputText}
  `.trim();
}

function buildMockStructuredCorrection(
  inputText: string,
  bedrockOutputText: string,
): CorrectionResultData {
  return {
    correctedKorean: bedrockOutputText,
    explanationEnglish:
      "This correction makes the Korean sentence more natural for the given context and learner level.",
    grammarPoints: [
      "Check whether the tense matches the time expression.",
      "Use polite endings consistently.",
      "Keep the sentence natural for everyday Korean.",
    ],
    naturalEnglishMeaning: inputText
      ? "Natural English meaning will be generated by Bedrock later."
      : "",
  };
}

function formatCorrectionOutput(result: CorrectionResultData): string {
  return [
    `Corrected Korean: ${result.correctedKorean}`,
    "",
    `Explanation: ${result.explanationEnglish}`,
    "",
    "Grammar Points:",
    ...result.grammarPoints.map((point) => `- ${point}`),
    "",
    `Natural English Meaning: ${result.naturalEnglishMeaning}`,
  ].join("\n");
}

export const correctKoreanText = async (
  input: CorrectionInput,
): Promise<CorrectionServiceResult> => {
  const userId = "dev-user-001";
  const inputText = input.text ?? "";

  const profile = await getOrCreateUserProfile(userId);

  await checkUsageLimit({
    userId,
    type: "correction",
  });

  const bedrockResult = await generateText({
    task: "correction",
    prompt: buildCorrectionPrompt(
      inputText,
      profile.levelLabel,
      profile.explanationLanguage,
    ),
  });

  const structuredResult = buildMockStructuredCorrection(
    inputText,
    bedrockResult.outputText,
  );

  const outputText = formatCorrectionOutput(structuredResult);

  await incrementUsage({
    userId,
    type: "correction",
  });

  await saveLearningRecord({
    userId,
    type: "correction",
    inputText,
    outputText,
    outputData: structuredResult,
    level: profile.levelLabel,
  });

  return {
    type: "correction",
    inputText,
    result: structuredResult,
    outputText,
    level: profile.levelLabel,
  };
};